# Generated by Django 6.0.4 on 2026-05-09 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_subscriber_downloadrequest_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('score', models.IntegerField(choices=[(1, '1 - Very bad'), (2, '2 - Bad'), (3, '3 - Normal'), (4, '4 - Good'), (5, '5 - Excellent')])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('download_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='pages.downloadrequest')),
            ],
            options={
                'verbose_name': 'Video rating',
                'verbose_name_plural': 'Video ratings',
            },
        ),
    ]
