# Generated by Django 6.0.4 on 2026-05-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_videorating'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrequest',
            name='downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='downloaded_file',
            field=models.FileField(blank=True, null=True, upload_to='downloads/'),
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='videoformat',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='videoformat',
            name='needs_ffmpeg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videoformat',
            name='ytdlp_format',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
